### PR TITLE
When adding an allocation replace allocations with a single allocation.

### PR DESCRIPTION
**Pull request by gurubobnz**
The Xero API is additive. You can only add new allocations, not append to an existing collection. Fix for https://github.com/calcinai/xero-php/issues/335 but needs more work before merging.

### CODE REVIEW

**Comment by calcinai** [comment]
@gurubobnz What more work do you think is required before merging?

**Comment by gurubobnz** [comment]
@calcinai I've confirmed that this code here works also https://github.com/calcinai/xero-php/issues/335#issuecomment-498990082 so need to rework this PR to do something similar. I'll give it a crack.

**Comment by gurubobnz** [comment]
Have tidied up the PR.

**Comment by timacdonald** [comment]
How would you add multiple *new* allocations in the one request with this?

```php
$overpayment->addAllocation($allocation_1);

$overpayment->addAllocation($allocation_2);
```

This would result in *only* `$allocation_2` being added right? Because `$allocation_1` would be removed when you add the second one?

I've never dealt with overpayment allocations so I'm not sure if anyone would ever even do this, but something to consider.

**Comment by gurubobnz** [comment]
Hmm yes you're right, that would not work. I will have a think about this.

**Comment by calcinai** [comment]
@gurubobnz any thoughts?

**Pull request closed without merging**
