### PR TITLE
Remove deprecated generator

### PR DESCRIPTION
**Pull request by timacdonald**
As the generator is no longer used, and you will always have it in version control, I'm proposing we just ditch it from the repo.

I know when I first accessed this library I actually thought the models were still generated automatically from the generator. So removing it may help clear that up for potential new contributors.

It also removes the `--dev` dependencies [`twig/twig`](https://github.com/twigphp/Twig) and [`fabpot/goutte`](https://github.com/FriendsOfPHP/Goutte). Now although these are only meant for development, and should not be install in production, if you are using something like [`roave/security-advisories`](https://github.com/Roave/SecurityAdvisories) it will error out and not let you install this package. The reason being, [as mentioned here](https://github.com/calcinai/xero-php/issues/559), the Twig version required has a security vulnerability.

As this is really internal code, I don't see this as a breaking change.

### CODE REVIEW

**Comment by calcinai** [comment]
Thanks Tim. I was about to do exactly the same thing.

**Comment by timacdonald** [comment]
No worries at all

**Comment by calcinai** [comment]
Sad (but happy) to see it go!

**Comment by timacdonald** [comment]
forever in our ~hearts~ git history

**Pull request merged**
