### PR TITLE
Moved authorize url query string logic to Client

### PR DESCRIPTION
**Pull request by timacdonald**
So in the `Application` there was logic to prepare the url retrieved from the `Client` via the `getAuthorizeURL()` method. I figure that the URL logic is kinda best to be taken care of by the `Client`, and that the `Application` just has a `getAuthorizeURL()` method as a (proxy) convenience.

Also, if someone was to call:

```php
$application->getOAuthClient()->getAuthorizeURL('MY_TOKEN');
```

it would not have had the query string attached as previously the `Application` was doing that, with this PR however, the query string would now be attached correctly.

Could probably extract a URL Helper class to deal with the url stuff I moved, but its a bit cleaner now anyway.

+ Tests!

### CODE REVIEW

**Comment by calcinai** [comment]
Nice

**Comment by timacdonald** [comment]
I'll fix up these conflicts tonight.

**Comment by timacdonald** [comment]
That's been fixed.

**Comment by timacdonald** [comment]
@calcinai I went a bit quiet on this cause I threw so much at ya at once haha.

What are your thoughts on this one? I don't see it being a breaking change.

**Comment by calcinai** [comment]
Let's do it

**Comment by timacdonald** [comment]
Damn! that was quick haha

**Pull request merged**
