### PR TITLE
Model Addition & Update

### PR DESCRIPTION
**Pull request by SidneyAllen**
Hi @calcinai 

Small improvement to the models.  Let me know what you think.

### CODE REVIEW

**Comment by calcinai** [comment]
Cheers @SidneyAllen, I'll test this today.

**Comment by SidneyAllen** [comment]
Hi @calcinai 

Any interest in adding myself as a committer to help review and merge PRs?

**Comment by calcinai** [comment]
Hey @SidneyAllen sorry I don't know how this didn't get merged! Will review all outstanding ones now.

**Comment by SidneyAllen** [comment]
Thanks 👍 - our team is building a demo app in php for our Developer Roadshow.  I'm going to look at adding "emailing invoices" and submitting a PR this week.

https://developer.xero.com/documentation/api/invoices#email

**Comment by calcinai** [comment]
Yeah discovered this earlier today! Did you see comments in #374?

Let me know if there's anything I can do to help. This project is basically a full time job with the issues/PRs and the number people that email me outside of Github!

**Comment by shabaz-ejaz** [comment]
@calcinai If you need any support / guidance with Integrating with Laravel specifically do let me know, I've managed to integrate using a lightweight wrapper that allows you to continue to use the classes and methods from this package as they are.

**Pull request merged**
