### PR TITLE
Removed member property for request in OAuth client

### PR DESCRIPTION
**Pull request by calcinai**
This PR removes the `$request` property from the OAuth client. This stops objects containing all of the previous request data.

This possibly addresses #271 too.

### CODE REVIEW

**Comment by calcinai** [comment]
What do you think about this @timacdonald

**Comment by timacdonald** [comment]
I do think this is good and a better way to go about things, rather then setting the request on the client.

The only issue I'd say is that it is changing the public API on `getSBS()` to `getSBS(Request $request)` so if you are doing Semantic Versioning with the project, it might be best targeted at the `2.0.0` release.

**Comment by calcinai** [comment]
Yes, you're right.  That should really be private - it's of zero use anywhere else.  Probably wouldn't even work..

**Comment by timacdonald** [comment]
Also, if the code 'feels' better because the client seems more like a utility to sign the request rather than something that owns the request. So passing it in feels better than having it saved to the object.

**Comment by timacdonald** [comment]
One thing on my list of things (yes...I started an ideas list hehe) is to review all the visibilities through, see if we can't clean up the public API

**Comment by calcinai** [comment]
Yeah exactly what I was thinking. Not sure what I was thinking a few years back when I wrote it - the whole point was to make something better than [this](https://github.com/XeroAPI/XeroOAuth-PHP/blob/master/lib/OAuthSimple.php)

**Comment by timacdonald** [comment]
Oh....I know! I love that Xero actually promote your project over their own in the docs! Man, I think the same thing when I look back at things I wrote 6 months ago.

**Comment by timacdonald** [comment]
This is an awesome project and I didn't really have any problems using it, it was dreamy. That serialize thing was my only issue, which I just sorted by passing the invoice ID between jobs instead of the invoice object.

**Comment by timacdonald** [comment]
I personally reckon if you got this thing tested out and perhaps an automated docs system and few other tweaks, you should hit up Xero and say - ours is fully tested, documented, modern PHP. Make this the official one and ditch theirs.

**Comment by calcinai** [comment]
On a semi-related note, I went to the 'XD17' talk the other day, and one of the main points they made was "DO NOT WRITE YOUR OWN SDK" 

Ha.

**Comment by timacdonald** [comment]
Check it, your at the top haha: https://developer.xero.com/documentation/libraries/php

Oh interesting, was their suggestion let the community? I wrote a [wrapper around the Kumulos API](https://github.com/timacdonald/kumulos-api) and they loved it and then wanted to take over the repo...I'm just like - just merge into this one...it's not like it's anything special anyway! Uh!

Put a license on it...never heard from them again haha

**Pull request merged**
