### PR TITLE
Allow bulk update of Models

### PR DESCRIPTION
**Pull request by coop182**
Small change to `Application->saveAll()` to allow bulk updates... not sure if this is documented with Xero... but it works!

### CODE REVIEW

**Comment by coop182** [comment]
I have updated it to stop constant reassignment... that was a bit lazy... but I don't want to do the first object comparison and exception if they are different.

If I do that it either has to be a bulk add or update... the way I have it now it can add and update.

That's what I saying about it not being documented by Xero as being possible... but it works... if you send a mixed array of objects some with and without GUID's it will update the ones with GUID's and new records for the ones without. I have successfully tested this against the ManualJournals endpoint.

**Comment by coop182** [comment]
Actually looking at the docs... it is clearly supported to create and update via POST... its actually kinda tempting to just change this to POST and take everything else out... but there are a few endpoints that only allow create... so I guess this is the best option.

**Comment by calcinai** [comment]
It feels a bit yuck, but I guess no reason not to allow it.  So just change the method on the first one you find with a GUID?

**Comment by coop182** [comment]
Yeah it is a bit yuck... but the benefits of being able to bulk sync data make it worth while I think. So yeah you if we find a GUID in the array of objects switch to POST otherwise PUT.

**Comment by calcinai** [comment]
Sounds good.

**Pull request merged**
