### PR TITLE
feat: support create and update for repeating invoice

### PR DESCRIPTION
**Pull request by kthiha-dev**

### CODE REVIEW

**Comment by calcinai** [comment]
Hi @kthiha-dev can you please check the formatting and then I'm happy to merge.

**Comment by kthiha-dev** [comment]
@calcinai sure, I will update it now. My VS code have reformat the whole things. I need to open with different editor. Give me a moment.

**Comment by kthiha-dev** [comment]
@calcinai Updated. Please check it.

**Comment by kthiha-dev** [comment]
@calcinai Would like to know when do you want to make release for this merge, if you don't mind. 👍

**Pull request merged**
