### PR TITLE
Handle the new pagination element

### PR DESCRIPTION
**Pull request by bretto36**
So any requests that are paginated are currently failing. Can this be merged in ASAP please @calcinai

### CODE REVIEW

**Comment by bretto36** [comment]
#916  #915 

This handles the changes Xero just released

**Comment by calcinai** [comment]
LGTM. Thanks @bretto36

**Comment by bretto36** [comment]
@calcinai  I can't run the tests locally as my version of php doesn't seem to like it. Are you able to run them. I've tested the XML stuff locally, but not sure how to test the parseJSON() method

Thanks for actioning so fast. Love when Xero releases something and doesn't give you a way to test beforehand

**Comment by bretto36** [comment]
@calcinai  Sorry for hounding you, can you also submit a new tag for release when you have time. Thanks so much!

**Comment by p4veI** [comment]
Hello @bretto36 and @calcinai came across this MR while debugging an empty invoice element parsed via the sdk, I believe the handling of pagination here is not completely correct, from what I'm seeing the child_index/key of the pagination is `pagination` i don't see any `PageInfo` really, see debug step attached. Can we resolve this somehow, the pagination element is being parsed as an empty invoice without any data.

Screenshot 2024-07-17 at 11 23 15

**Comment by bretto36** [comment]
Yes I have a new PR up because Xero have changed the value again. 

Just waiting for @calcinai to merge. Hopefully he's online at some stage. 

Or you can use my fork in the meantime

**Comment by p4veI** [comment]
Cool, missed that one, thanks!

**Pull request merged**
