### PR TITLE
Feature/payroll uk

### PR DESCRIPTION
**Pull request by dextermb**
As requested [here](https://github.com/calcinai/xero-php/issues/322#issuecomment-475912713).

_Ignore the package JSON renaming. Instead of installing it under my own package I now just overwrite the repository_

### CODE REVIEW

**Comment by calcinai** [comment]
Don't worry about the conflicts for now, I'll review first.

**Comment by dextermb** [comment]
@calcinai, any news?

**Comment by calcinai** [comment]
@dextermb I'm so sorry, I have been absolutely flat tack. 

Looking now.

**Comment by dextermb** [comment]
> @dextermb I'm so sorry, I have been absolutely flat tack.
> 
> Looking now.

No problem, would just be best to get it in ASAP if it doesn't change too much as then people can start contributing to finish it off.

I've also noticed that PayrollUK is no longer in beta, whereas this was written during beta.

**Comment by ash123456789** [comment]
@calcinai Any updates on this?

**Comment by calcinai** [comment]
@dextermb So this looks good I think.  Are you able to resolve those conflicts and then I'll merge it in.  Cheers for your work

**Comment by iangregory** [comment]
@dextermb are you still maintaining your fork? Would be great to see this merged

**Comment by calcinai** [comment]
@iangregory @dextermb happy to review this again if you can resolve the conflicts

**Comment by dextermb** [comment]
> @iangregory @dextermb happy to review this again if you can resolve the conflicts

Hey, I'm not going to go through it again. Feel free to branch off what I've done and continue. I assume a decent amount of stuff has changed since this was first opened.

**Pull request closed without merging**
