### PR TITLE
Payroll PayItems fix

### PR DESCRIPTION
**Pull request by iamthefox**
Hello,

I submitted similar request for the payslip endpoint last night. 

Basically API returns results in as a single node. 

Might be worth looking in more abstract solution for this problem. 

Thank you,
Alex

### CODE REVIEW

**Comment by calcinai** [comment]
Have you used other payroll classes?  Do you know if this behaviour is actually documented anywhere?

**Comment by iamthefox** [comment]
yup, I used PayRuns, PayItems, Payslip (in singular) and Employee. They have API preview tool but you will need to register an account, to see what output is going to look like

**Comment by iamthefox** [comment]
by the way, only these 2 had issues with it

**Comment by calcinai** [comment]
What a pain in the.

**Comment by iamthefox** [comment]
yeah, unfortunately it is not the most consistent API :(

**Comment by calcinai** [comment]
Well thanks for adding these workarounds.  It's thinks like this that are slowing down 2.0!

**Pull request merged**
