### PR TITLE
Fix set config option incorrect variable

### PR DESCRIPTION
**Pull request by timacdonald**
The `setConfigOption` references a variable that doesn't exist when throwing exception. Fixed that and added tests for the method.

### CODE REVIEW

**Comment by timacdonald** [comment]
I'll fix up these conflicts tonight.

**Comment by timacdonald** [comment]
That's been fixed.

**Comment by calcinai** [comment]
I should've picked up on this!

**Comment by timacdonald** [comment]
we've all done that before man, I've done it countless times...and will probably continue to haha

**Pull request merged**
