### PR TITLE
More unique nonce generation, date query params, reports

### PR DESCRIPTION
**Pull request by specialtactics**
I've had a lot of errors from the xero api saying my nonce has already been used when making many requests in a row, and I've tried a number of approaches at better nonce generation, and this seems to be working quite well.

### CODE REVIEW

**Comment by specialtactics** [comment]
Also added to & from query parameters.

I've also added functionality to use Reports. They seem to be fairly generic, so I've just included code for the 2 I've used so far, I will be looking further into it in the coming weeks.

**Comment by calcinai** [comment]
Thanks for your work on this.  The noonce generation was following Xero's library, I will test to make sure it had no other repercussions. 

The report thing was something that's been missing for a while, I hadn't got around to parsing it out of the docs!

One comment re: the toDate and fromDate, how would you feel about them being date time objects passed, then formatted when the query is executed - that would be more in line with the conventions elsewhere.

**Comment by specialtactics** [comment]
Hi there

I do prefer the use of DateTime, though in this case because Xero only took date, I figured it may be confusing in the sense that people might assume you can specify a time where it actually would get discarded. So I'm happy to defer to you on this one, I don't really mind either way.

**Comment by specialtactics** [comment]
Just wondering what the status of this is. Would you still prefer to be using the DateTime objects following on from that discussion, and are you looking for me to implement that?

**Comment by calcinai** [comment]
Sorry about not getting back to you. I've been away for the last week. If you didn't mind changing them to DateTimes, that would be great. Otherwise it's fine to merge.

**Comment by specialtactics** [comment]
No worries, I've updated the PR, switched to DateTime (looking pretty clean), and added another date query param.

**Pull request merged**
