### PR TITLE
Change XeroPHP\Remote\Object to  XeroPHP\Remote\Model

### PR DESCRIPTION
**Pull request by mattmcardle**
Fixes https://github.com/calcinai/xero-php/issues/326

### CODE REVIEW

**Comment by calcinai** [comment]
This looks good, do you think it's worth adding an autoloader class `Object` extending `Model` for backward compatibility?

**Comment by mattmcardle** [comment]
Added an empty abstract Object class that extends Model for backwards compatibility, is this what you meant @calcinai? I was a bit confused when you said "autoloader" class.

**Comment by calcinai** [comment]
To be honest, I am also a bit confused by that comment.

But yes, that's what I meant, if you think it makes sense?

**Comment by mattmcardle** [comment]
Yeah, I think its a good idea as it will prevent forcing people to make changes to references to  any references to `Object` they might have in their own code if they upgrade this package and are on < 7.2.

**Comment by mattmcardle** [comment]
Just thinking, perhaps I should add a comment into the Object class to inform people it is only there for backwards compatibility? We could also take the opportunity to advise them to use the new Model class if they run into issues after upgrading to PHP 7.2 in the same comment, what do you think?

**Comment by calcinai** [comment]
Absolutely - just adding the `@deprecated` tag to the class will inform most IDEs

**Comment by mattmcardle** [comment]
Done, can you merge and do a release when you get a chance? I'm currently pointing to my fork :-1:

**Pull request merged**
