### PR TITLE
getNonce(): Only use mt_rand to generate a random string

### LINKED ISSUE #235: getNonce() assumes microtime() will have a decimal part
The getNonce() method in XeroPHP/Remote/OAuth/Client.php assumes that microtime will return a decimal part, and explodes on the decimal point:
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Remote/OAuth/Client.php#L232

However, it is possible that microtime will land exactly on the second, and no decimal part will be returned.

### PR DESCRIPTION
**Pull request by Josh-G**
Fixes #235

### CODE REVIEW

**Comment by Josh-G** [comment]
Is just having mt_rand not random enough?

https://github.com/calcinai/xero-php/commit/71db90c3a0f962048786c6203ab8a4c0a027d4b5#diff-48c7813bb7d60d193f619de8f20cecd4

**Comment by calcinai** [comment]
I never actually encountered this issue - as you saw, it was changed last year because I assume the noonce was colliding..

**Comment by Josh-G** [comment]
Would it not be less random replacing 4 random characters from mt_rand with the current time?

Was Xero saying you were colliding? Isn't the probability of that incredibly rare? Sorry, I'm a little confused here :D

**Comment by Josh-G** [comment]
I think this change makes more sense. It's currently an issue for us as we elevate warnings into exceptions and this warning occurs 10-20 times a day despite it's rarity.

**Pull request merged**
