### PR TITLE
add NumberOfUnits property to fix #673

### LINKED ISSUE #673: TimesheetEarningsLines is missing the NumberOfUnits property
The Xero API and its documentation have a NumberOfUnits property in each of the Timesheet Earnings Lines of a Payslip but XeroPHP has no property, get or set method for this.

Heres the Xero Documentation: https://developer.xero.com/documentation/payroll-api/payslip#TimesheetEarningsLine

And the XeroPHP file to locate is: TimesheetsEarningsLine.php in the Payslip folder of PayrollAU.

### PR DESCRIPTION
**Pull request by rodjsta**
remove getter and setter for Amount property and add NumberOfUnits property with getter and setter as mentioned in Issue #673

### CODE REVIEW

**Comment by calcinai** [comment]
@rodjsta This is an api-incompatible change.  Can you please deprecate the old methods and add new ones for backward combat?

**Comment by calcinai** [comment]
@rodjsta any progress on this?

**Comment by Healyhatman** [comment]
@calcinai in #717 I've kept the old getter / setter and added a @deprecated tag

**Comment by calcinai** [comment]
In favour of #717

**Pull request closed without merging**
