### PR TITLE
isPropertyDirty dose not exists should be isDirty

### PR DESCRIPTION
**Pull request by tiran133**
In Your application you call a method isPropertyDirty
https://github.com/calcinai/xero-php/blob/master/src/XeroPHP/Application.php#L276

I tried to allocate a overpayment to an invoice. Since this Property is save Directly it tries to call this method.

But it should just be isDirty($porperty)

Alex

### CODE REVIEW

**Comment by calcinai** [comment]
Thanks for spotting this one.  Bust have been a BC introduced at some point.

**Comment by tiran133** [comment]
Hey Thank you. 

Is it possible you tag this version so i will get the fix with an composer update?

Thanks
Alex

**Comment by calcinai** [comment]
Hey, it's actually tagged as 1.3.0, since there are some other updated that might affect users of the 1.2 release.

I'll update the readme now to reflect this.

**Comment by tiran133** [comment]
Hey thanks i just saw that. I will try this version see if it breaks anything in my app.

**Pull request merged**
