### PR TITLE
Adding FromIsReconciled and ToIsReconciled to BankTransfer

### PR DESCRIPTION
**Pull request by incentfit**
Fixes https://github.com/calcinai/xero-php/issues/883

This is tested and based on the Xero API docs at https://developer.xero.com/documentation/api/accounting/banktransfers

### CODE REVIEW

**Comment by calcinai** [comment]
Great, thanks @incentfit

**Comment by incentfit** [comment]
@calcinai any plans for a release in the near future?

**Comment by calcinai** [comment]
Hi @incentfit there's one more PR then I'll do a release

**Comment by incentfit** [comment]
@calcinai can you share a ballpark timeframe of when that will be?

**Comment by calcinai** [comment]
@incentfit Looks like there will be some breaking changes in the PR I was waiting on, so I'll push this out now!

**Pull request merged**
