### PR TITLE
PayrollAU Payslip Fix TimesheetEarningsLine not being found

### PR DESCRIPTION
**Pull request by JimboM4CK**
This fixes Xero-PHP not handling TimesheetEarningsLines/EarningsLine correctly. See issue #407.

### CODE REVIEW

**Comment by JimboM4CK** [comment]
Don't use this yet. I've realised this may conflict with international versions. This only fixes Payroll AU.

**Comment by JimboM4CK** [comment]
What do the international endpoints point to? Is it TimesheetEarningsLine or EarningsLine?

**Comment by calcinai** [comment]
@JimboM4CK I have no idea sorry! What do the docs say?

**Comment by calcinai** [comment]
@JimboM4CK what's the status here?

**Pull request closed without merging**
