### PR TITLE
Update Item.php

### PR DESCRIPTION
**Pull request by theshelf**
Changed addSalesDetail and addPurchaseDetail to add value to a collection
Added setSalesDetails and setPurchaseDetails to set the entire collection

### CODE REVIEW

**Comment by calcinai** [comment]
Is this correct? It looks like you can end up with either a collection or a single object as this property...

**Comment by calcinai** [comment]
Can I be picky and ask that you leave in the old functions but add the deprecated tag? They wouldn't have been working (I can't see how) anyway, so I think it's safe for them to be empty, but don't want to throw fatals.

**Comment by theshelf** [comment]
You're correct - I had left the edited addSalesDetail/addPurchaseDetail functions when they aren't required at all - it's a switch from 

Have added a patch that removes the addSalesDetail/addPurchaseDetail functions and replaces them with the setSalesDetails/setPurchaseDetails.

**Comment by calcinai** [comment]
Perfect, thanks.

**Pull request merged**
