### PR TITLE
Expose x-rate-limit-problem header

### LINKED ISSUE #352: Rate Limit Counter
I'm struggling with the Xero Rate Limit, and unsure why as I'm not querying often enough to hit their limit.  Is there anything built into Xero-PHP to allow me to output the rate that I am querying at?  Ie a counter etc.

### PR DESCRIPTION
**Pull request by Josh-G**
Extension of #353 that maintains compatibility. This change adds it as a field rather than to the exception message.

Our use case is to monitor the number of merchants we are routinely hitting the rate limit for and expose this info to our support team.

Fixes #352.

### CODE REVIEW

**Comment by Josh-G** [comment]
@calcinai any input?

**Comment by calcinai** [comment]
@Josh-G sorry I'll take a loo later today. I see a couple of the function signatures have changed so need to make sure there are no implications of that.

**Comment by calcinai** [comment]
_later today_

**Comment by Josh-G** [comment]
@calcinai could I request a release for this please? 😄

**Pull request merged**
